<a href="https://colab.research.google.com/github/baanujan-18/Statistical-Learning-e20030/blob/main/Data_Analysis_Cookbook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Sanitization and Exploration Engine

## Project Plan

This project aims to develop a modular Python-based **Data Sanitization and Exploration Engine** using Object-Oriented Programming concepts. The main objective of this project is to create a reusable data analysis tool that can load, clean, preprocess, visualize, and analyze CSV datasets in an efficient and structured manner.

The system will be mainly developed and tested in the **Google Colab environment**. The final version of the project will be organized as a GitHub repository with reusable Python files, a demonstration notebook, a README file, and required dependency files.

The project will be implemented using two main reusable classes:

- `DataInspector`
- `PlottingMethods`

The `DataInspector` class will be responsible for data loading, data cleaning, preprocessing, missing value handling, duplicate removal, outlier detection, normalization, encoding, and preparation of the final processed dataset.

The `PlottingMethods` class will be responsible for generating interactive visualizations such as histograms, box plots, violin plots, scatter plots, bar charts, categorical frequency charts, and association heatmaps.

---

## Dataset Selection

A sample dataset obtained from Kaggle or another open-source data repository will be used to test and demonstrate the complete workflow of the project.

For the initial implementation, the **Titanic dataset** will be used because it contains:

- Numerical variables
- Categorical variables
- Missing values
- Different feature types
- Useful columns for visualization and preprocessing

Therefore, the Titanic dataset is suitable for demonstrating data cleaning, preprocessing, visualization, and statistical analysis.

---

## Planned Workflow

The project will follow the workflow shown below:

$$
\text{Upload Dataset}
\rightarrow
\text{Clean Invalid Values}
\rightarrow
\text{Correct Data Types}
\rightarrow
\text{Inspect Dataset}
\rightarrow
\text{Handle Missing Values}
\rightarrow
\text{Remove Duplicates}
$$

$$
\rightarrow
\text{Handle Outliers}
\rightarrow
\text{Normalize Numerical Data}
\rightarrow
\text{Encode Categorical Data}
\rightarrow
\text{Visualize Data}
\rightarrow
\text{Generate Association Heatmap}
$$

---

## Main Functionalities to be Developed

### 1. Data Loading and Sanitization

The first stage of the project is to load a CSV dataset into the system. The tool will allow users to upload CSV files directly in Google Colab.

After loading the dataset, common invalid values will be automatically converted into proper missing values represented by `NaN`.

Examples of invalid values include:

- `"?"`
- `"n/a"`
- `"N/A"`
- `"NULL"`
- `"null"`
- Empty strings
- Blank spaces

Suitable columns will also be automatically converted into numerical data types wherever possible. This helps to reduce manual preprocessing work and improves the reliability of later analysis.

---

### 2. Dataset Inspection

After loading and cleaning the dataset, the system will provide basic information about the dataset.

This includes:

- Number of rows and columns
- Column names
- Data types
- Missing value counts
- Numerical summaries
- Categorical summaries

The system will also automatically identify numerical and categorical columns. This is important because different preprocessing and visualization techniques are applied depending on the type of data.

---

### 3. Missing Value Handling

The project will include missing value handling methods. Missing values in numerical and categorical columns will be treated using different strategies.

The planned missing value handling methods are:

$$
\text{Mean Imputation}
$$

$$
\text{Median Imputation}
$$

$$
\text{Mode Imputation}
$$

$$
\text{Constant Value Replacement}
$$

These methods will allow the user to clean the dataset according to the nature of the selected column.

---

### 4. Duplicate and Outlier Handling

The system will include a function to remove duplicate records from the dataset. Duplicate records can affect the quality of analysis, so removing them is an important preprocessing step.

Outlier detection will be performed using the **Interquartile Range method**.

The IQR method identifies abnormal values using the following equations:

$$
IQR = Q_3 - Q_1
$$

$$
\text{Lower Bound} = Q_1 - 1.5 \times IQR
$$

$$
\text{Upper Bound} = Q_3 + 1.5 \times IQR
$$

Values below the lower bound or above the upper bound will be identified as possible outliers. The system will allow users to detect and optionally remove these outliers.

---

### 5. Feature Engineering Preparation

The project will include normalization and encoding methods to prepare the dataset for machine learning or further analysis.

Numerical columns will be normalized using:

- Min-Max Scaling
- Standard Scaling
- Robust Scaling

Categorical columns will be encoded using:

- One-Hot Encoding
- Ordinal Encoding
- Uniform Encoding

After applying scaling and encoding, the processed numerical and categorical data will be combined into a final cleaned DataFrame.

---

### 6. Interactive Data Visualization

Interactive visualizations will be developed using **Plotly**. The visualization module will allow users to analyze the dataset visually.

The planned plots include:

- Histogram
- Box Plot
- Violin Plot
- Scatter Plot
- Grouped Bar Chart
- Categorical Frequency Chart

These charts will help users understand distributions, relationships, variations, and category-wise patterns in the dataset.

---

### 7. Association Heatmap

The final stage of the project is to create a unified association heatmap. This heatmap will be used to analyze relationships between numerical and categorical variables.

Different statistical techniques will be used depending on the variable types:

$$
\text{Numerical vs Numerical} \rightarrow \text{Pearson Correlation}
$$

$$
\text{Categorical vs Categorical} \rightarrow \text{Cramer's V}
$$

$$
\text{Numerical vs Categorical} \rightarrow \text{Point-Biserial Correlation or Eta Correlation}
$$

This heatmap will provide deeper insight into the relationships between different features in the dataset.

---

## Expected Final Output

At the end of this project, a reusable Python-based data analysis engine will be developed.

The final system will be able to:

- Upload and load CSV datasets
- Clean invalid values
- Identify numerical and categorical columns
- Show dataset summaries
- Handle missing values
- Remove duplicate records
- Detect and handle outliers
- Normalize numerical features
- Encode categorical features
- Generate interactive visualizations
- Create association heatmaps
- Produce a final cleaned and processed dataset

---

## Final Project Goal

The final goal of this project is to build a reusable and efficient Python framework for real-world data cleaning, preprocessing, and exploratory data analysis.

The system will demonstrate the use of Object-Oriented Programming concepts by separating data inspection and visualization tasks into reusable classes.

The completed project will be uploaded to GitHub with a proper project structure, including:

- Main Python package
- Demonstration notebook
- README file
- Requirements file
- License
- Version information

## Dataset Source and Selection

For the initial implementation of this project, the **Titanic dataset** will be used to test and demonstrate the complete workflow of the Data Sanitization and Exploration Engine.

The Titanic dataset is one of the most commonly used beginner datasets in data science and machine learning. It is useful for learning data cleaning, exploratory data analysis, feature engineering, visualization, and machine learning preprocessing.

In this project, the Titanic dataset will be obtained from an **open-source GitHub repository** instead of Kaggle. GitHub is selected as the dataset source because it allows the CSV file to be loaded directly into Google Colab using a public raw file link. This makes the implementation easier, faster, and more suitable for demonstrating an automated data analysis workflow.

The dataset will be loaded into Google Colab using the following Python code:

```python
import pandas as pd

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

df.head()

In [3]:
# Step 1: Import Required Libraries

import pandas as pd  # Reading CSV files ,storing data in DataFrames,checking missing values,cleaning data,handling columns and rows
import numpy as np   # NumPy is used for numerical operations

In [4]:
# Step 2: Load Titanic Dataset from GitHub

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv" # We are using the Titanic dataset from GitHub

df = pd.read_csv(url) # The dataset is stored inside a Pandas DataFrame called df

df.head() # This displays the first five rows of the dataset so we use this to quickly check whether the dataset loaded correctly.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
# Step 3: Create Basic DataInspector Class

class DataInspector:    # This creates a class named DataInspector. A class is like a reusable container.
                        # { inspector = DataInspector() }-  when this line runs, the __init__() function automatically runs.

    def __init__(self): # This is the constructor method. It runs automatically when we create an object from the class.
        self.df = None  # This creates an empty variable inside the class , self.df will later store the dataset. At the beginning, it is empty, so we write None.

In [6]:
# Step 4: DataInspector Class with Dataset Loading

class DataInspector:

    def __init__(self):
        self.df = None

    def load_from_url(self, url):              # This creates a function inside the class. The purpose of this function is to load a dataset from a URL.
        self.df = pd.read_csv(url)             # This reads the CSV file from the given URL and stores it inside self.df. This is important because all other functions will use self.df.
        print("Dataset loaded successfully.")  # This prints a message to confirm that the dataset has loaded.
        return self.df                         # This returns the loaded dataset so we can display or use it.

In [7]:
# Step 5: Test Data Loading

inspector = DataInspector() # This creates an object from the DataInspector class. Now inspector can use all functions inside the class.

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

df = inspector.load_from_url(url) # This calls the load_from_url() function. It loads the Titanic dataset and stores it inside.

df.head()

Dataset loaded successfully.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# clean Invalid Values

In [8]:
# ==========================================
# Step 6: Add Invalid Value Cleaning Function
# ==========================================

class DataInspector:

    def __init__(self):
        self.df = None

    def load_from_url(self, url):
        self.df = pd.read_csv(url)
        print("Dataset loaded successfully.")
        return self.df

    def clean_invalid_values(self):
        invalid_values = ["?", "n/a", "N/A", "NA", "NULL", "null", "", " "]

        self.df.replace(invalid_values, np.nan, inplace=True)

        print("Invalid values converted to NaN successfully.")

        return self.df

# Step 7: Create a New Object and Test Invalid-Value Cleaning

In [10]:
# Step 7: Test Invalid-Value Cleaning

inspector = DataInspector()  # Creates a new object using the latest version of the DataInspector class

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"  # Stores the GitHub CSV link

df = inspector.load_from_url(url)  # Loads the Titanic dataset and stores it inside inspector.df

df = inspector.clean_invalid_values()  # Replaces invalid values such as ?, N/A and NULL with np.nan

df.head()  # Displays the first five rows of the cleaned dataset

Dataset loaded successfully.
Invalid values converted to NaN successfully.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Step 8: Check Missing Values in Each Column

In [11]:
# ==========================================
# Step 8: Check Missing Values in Each Column
# ==========================================

df.isnull().sum()  # Counts the number of missing values in each column

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Step 9: Improve the Cleaning Function with a Safety Check

In [12]:
# ==========================================
# Step 9: Improve Invalid-Value Cleaning
# ==========================================

class DataInspector:

    def __init__(self):
        self.df = None  # No dataset is stored when the object is first created

    def load_from_url(self, url):
        self.df = pd.read_csv(url)  # Reads the CSV dataset from the given URL
        print("Dataset loaded successfully.")  # Displays a success message
        return self.df  # Returns the loaded DataFrame

    def clean_invalid_values(self):

        # Checks whether a dataset has been loaded before starting the cleaning process
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Stores common invalid values that may appear in real-world datasets
        invalid_values = [
            "?",
            "n/a",
            "N/A",
            "NA",
            "NULL",
            "null",
            "",
            " "
        ]

        # Searches the entire DataFrame and replaces invalid values with np.nan
        self.df.replace(invalid_values, np.nan, inplace=True)

        # Displays a message after the cleaning process is completed
        print("Invalid values converted to NaN successfully.")

        # Returns the cleaned DataFrame
        return self.df

# Step 10: Test the Safety Check

In [13]:
# ==========================================
# Step 10: Test the Safety Check
# ==========================================

test_inspector = DataInspector()  # Creates a new object without loading a dataset

test_inspector.clean_invalid_values()  # Attempts to clean data before loading a dataset

No dataset is loaded. Please load a dataset first.

# Step 11: Test the Complete Cleaning Process Again

In [14]:
# ==========================================
# Step 11: Run the Complete Cleaning Process
# ==========================================

inspector = DataInspector()  # Creates a new DataInspector object

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"  # Stores the dataset URL

df = inspector.load_from_url(url)  # Loads the Titanic dataset

df = inspector.clean_invalid_values()  # Cleans invalid values

df.isnull().sum()  # Displays the number of missing values in each column

Dataset loaded successfully.
Invalid values converted to NaN successfully.

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

# Step 12: Add Automatic Data-Type Correction

In [15]:
# ==========================================
# Step 12: Add Automatic Data-Type Correction
# ==========================================

class DataInspector:

    def __init__(self):
        self.df = None  # No dataset is stored when the object is first created

    def load_from_url(self, url):
        self.df = pd.read_csv(url)  # Reads the CSV dataset from the given URL
        print("Dataset loaded successfully.")  # Displays a confirmation message
        return self.df  # Returns the loaded DataFrame

    def clean_invalid_values(self):

        # Checks whether a dataset has been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Stores common invalid values found in real-world datasets
        invalid_values = [
            "?",
            "n/a",
            "N/A",
            "NA",
            "NULL",
            "null",
            "",
            " "
        ]

        # Replaces invalid values with proper missing values
        self.df.replace(invalid_values, np.nan, inplace=True)

        print("Invalid values converted to NaN successfully.")

        return self.df

    def correct_data_types(self):

        # Checks whether a dataset has been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Goes through each column in the dataset one by one
        for column in self.df.columns:

            # Attempts to convert the current column into numerical values
            converted_column = pd.to_numeric(self.df[column], errors="coerce")

            # Counts the number of available values in the original column
            original_non_null_count = self.df[column].notna().sum()

            # Counts the number of available values after attempting numerical conversion
            converted_non_null_count = converted_column.notna().sum()

            # Converts the column only if all available values can be safely converted
            if original_non_null_count == converted_non_null_count:
                self.df[column] = converted_column

        print("Suitable columns converted into numerical data types successfully.")

        return self.df

# Step 13: Test Automatic Data-Type Correction

In [16]:
# ==========================================
# Step 13: Test Automatic Data-Type Correction
# ==========================================

inspector = DataInspector()  # Creates a new object using the updated class

url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"  # Stores the dataset URL

df = inspector.load_from_url(url)  # Loads the dataset

df = inspector.clean_invalid_values()  # Cleans invalid values

df = inspector.correct_data_types()  # Converts suitable columns into numerical formats

df.dtypes  # Displays the data type of each column

Dataset loaded successfully.
Invalid values converted to NaN successfully.
Suitable columns converted into numerical data types successfully.

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

# Step 14: Add Dataset Inspection Functions

In [17]:
# ==========================================================
# Step 14: Add Dataset Inspection and Summary Functions
# ==========================================================

class DataInspector:

    # This method runs automatically when a new object is created
    def __init__(self):

        # At the beginning, no dataset is loaded
        self.df = None


    # ----------------------------------------------------------
    # Load a CSV dataset from a GitHub URL
    # ----------------------------------------------------------
    def load_from_url(self, url):

        # Read the CSV file from the given URL
        self.df = pd.read_csv(url)

        # Display a confirmation message
        print("Dataset loaded successfully.")

        # Return the loaded DataFrame
        return self.df


    # ----------------------------------------------------------
    # Convert invalid text values into proper missing values
    # ----------------------------------------------------------
    def clean_invalid_values(self):

        # Check whether a dataset has already been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # List of common invalid values found in datasets
        invalid_values = [
            "?",
            "n/a",
            "N/A",
            "NA",
            "NULL",
            "null",
            "",
            " "
        ]

        # Replace invalid values with np.nan
        self.df.replace(invalid_values, np.nan, inplace=True)

        # Display a confirmation message
        print("Invalid values converted to NaN successfully.")

        # Return the cleaned DataFrame
        return self.df


    # ----------------------------------------------------------
    # Convert suitable columns into numerical data types
    # ----------------------------------------------------------
    def correct_data_types(self):

        # Check whether a dataset has already been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Go through each column one by one
        for column in self.df.columns:

            # Try to convert the current column into numerical values
            converted_column = pd.to_numeric(
                self.df[column],
                errors="coerce"
            )

            # Count available values before conversion
            original_non_null_count = self.df[column].notna().sum()

            # Count available values after conversion
            converted_non_null_count = converted_column.notna().sum()

            # Convert the column only if all available values can be
            # safely converted into numbers
            if original_non_null_count == converted_non_null_count:
                self.df[column] = converted_column

        # Display a confirmation message
        print("Suitable columns converted into numerical data types successfully.")

        # Return the updated DataFrame
        return self.df


    # ----------------------------------------------------------
    # Display the main summary of the dataset
    # ----------------------------------------------------------
    def get_summary(self):

        # Check whether a dataset has already been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Display a heading
        print("========== DATASET SUMMARY ==========")

        # Display the number of rows and columns
        print("\nDataset Shape:")
        print(f"Number of rows    : {self.df.shape[0]}")
        print(f"Number of columns : {self.df.shape[1]}")

        # Display all column names
        print("\nColumn Names:")
        print(self.df.columns.tolist())

        # Display information about the dataset
        print("\nDataset Information:")
        self.df.info()

        # Display numerical and categorical statistical summaries
        print("\nStatistical Summary:")
        display(self.df.describe(include="all").transpose())


    # ----------------------------------------------------------
    # Display detailed information about each column
    # ----------------------------------------------------------
    def column_details(self):

        # Check whether a dataset has already been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Create an empty list to store column details
        details = []

        # Go through each column one by one
        for column in self.df.columns:

            # Store useful information about the current column
            details.append({
                "Column Name": column,
                "Data Type": str(self.df[column].dtype),
                "Non-Missing Values": self.df[column].notna().sum(),
                "Missing Values": self.df[column].isna().sum(),
                "Unique Values": self.df[column].nunique()
            })

        # Convert the list into a DataFrame
        details_df = pd.DataFrame(details)

        # Display the column details table
        display(details_df)

        # Return the table
        return details_df


    # ----------------------------------------------------------
    # Display summaries for categorical columns
    # ----------------------------------------------------------
    def get_categorical_summary(self):

        # Check whether a dataset has already been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Select columns that contain categorical or text values
        categorical_columns = self.df.select_dtypes(
            include=["object", "category", "bool"]
        ).columns.tolist()

        # Display the identified categorical columns
        print("Categorical Columns:")
        print(categorical_columns)

        # Check whether categorical columns exist
        if len(categorical_columns) == 0:
            print("No categorical columns found.")
            return None

        # Go through each categorical column one by one
        for column in categorical_columns:

            # Display the current column name
            print(f"\n========== {column} ==========")

            # Display the frequency of each value
            display(
                self.df[column]
                .value_counts(dropna=False)
                .rename_axis("Value")
                .reset_index(name="Count")
            )


    # ----------------------------------------------------------
    # Display missing-value counts and percentages
    # ----------------------------------------------------------
    def show_missing_data(self):

        # Check whether a dataset has already been loaded
        if self.df is None:
            print("No dataset is loaded. Please load a dataset first.")
            return None

        # Count missing values in each column
        missing_count = self.df.isna().sum()

        # Calculate the percentage of missing values in each column
        missing_percentage = (
            self.df.isna().sum() / len(self.df)
        ) * 100

        # Create a summary DataFrame
        missing_summary = pd.DataFrame({
            "Missing Values": missing_count,
            "Missing Percentage (%)": missing_percentage.round(2)
        })

        # Display only columns that contain missing values
        missing_summary = missing_summary[
            missing_summary["Missing Values"] > 0
        ]

        # Display the final missing-value summary table
        display(missing_summary)

        # Return the missing-value summary table
        return missing_summary

# Step 15: Create a New Object and Prepare the Dataset Again

In [18]:
# ==========================================================
# Step 15: Load and Prepare the Dataset
# ==========================================================

# Create a new object using the latest version of the class
inspector = DataInspector()

# Store the Titanic dataset GitHub link
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"

# Load the dataset from GitHub
df = inspector.load_from_url(url)

# Convert invalid values such as ?, N/A and NULL into np.nan
df = inspector.clean_invalid_values()

# Convert suitable columns into numerical data types
df = inspector.correct_data_types()

# Display the first five rows
df.head()

Dataset loaded successfully.
Invalid values converted to NaN successfully.
Suitable columns converted into numerical data types successfully.

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

# Step 16: Display the Main Dataset Summary

In [19]:
# ==========================================================
# Step 16: Display the Main Dataset Summary
# ==========================================================

inspector.get_summary()  # Displays the shape, columns, data types and statistical summary

========== DATASET SUMMARY ==========

Dataset Shape:
Number of rows    : 891
Number of columns : 12

Column Names:
['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

Statistical Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
PassengerId,891.0,NaN,NaN,NaN,446.0,257.353842,1.0,223.5,446.0,668.5,891.0
Survived,891.0,NaN,NaN,NaN,0.383838,0.486592,0.0,0.0,0.0,1.0,1.0
Pclass,891.0,NaN,NaN,NaN,2.308642,0.836071,1.0,2.0,3.0,3.0,3.0
Name,891,891,"Dooley, Mr. Patrick",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Sex,891,2,male,577,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,714.0,NaN,NaN,NaN,29.699118,14.526497,0.42,20.125,28.0,38.0,80.0
SibSp,891.0,NaN,NaN,NaN,0.523008,1.102743,0.0,0.0,0.0,1.0,8.0
Parch,891.0,NaN,NaN,NaN,0.381594,0.806057,0.0,0.0,0.0,0.0,6.0
Ticket,891,681,347082,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Fare,891.0,NaN,NaN,NaN,32.204208,49.693429,0.0,7.9104,14.4542,31.0,512.3292
Cabin,204,147,G6,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Embarked,889,3,S,644,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Step 17: Display Column Details

In [20]:
# ==========================================================
# Step 17: Display Detailed Information for Each Column
# ==========================================================

column_details_df = inspector.column_details()  # Creates and displays a table containing details about every column

    Column Name Data Type  Non-Missing Values  Missing Values  Unique Values
0   PassengerId     int64                 891               0            891
1      Survived     int64                 891               0              2
2        Pclass     int64                 891               0              3
3          Name    object                 891               0            891
4           Sex    object                 891               0              2
5           Age   float64                 714             177             88
6         SibSp     int64                 891               0              7
7         Parch     int64                 891               0              7
8        Ticket    object                 891               0            681
9          Fare   float64                 891               0            248
10        Cabin    object                 204             687            147
11     Embarked    object                 889               2              3

# Step 18: Display Categorical Summary

In [21]:
# ==========================================================
# Step 18: Display Summaries for Categorical Columns
# ==========================================================

inspector.get_categorical_summary()  # Displays value counts for each categorical column

Categorical Columns:
['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked']

========== Name ==========

                                                 Value  Count
0                                  Dooley, Mr. Patrick      1
1                              Braund, Mr. Owen Harris      1
2    Cumings, Mrs. John Bradley (Florence Briggs Th...      1
3                               Heikkinen, Miss. Laina      1
4         Futrelle, Mrs. Jacques Heath (Lily May Peel)      1
..                                                 ...    ...
886                   Hewlett, Mrs. (Mary D Kingcome)       1
887               Vestrom, Miss. Hulda Amanda Adolfina      1
888                        Andersson, Mr. Anders Johan      1
889                     Saundercock, Mr. William Henry      1
890                           Bonnell, Miss. Elizabeth      1

[891 rows x 2 columns]

========== Sex ==========

    Value  Count
0    male    577
1  female    314

========== Ticket ==========

                Value  Count
0              347082      7
1                1601      7
2            CA. 2343      7
3             3101295      6
4             CA 2144      6
..                ...    ...
676          PC 17590      1
677             17463      1
678            330877      1
679            373450      1
680  STON/O2. 3101282      1

[681 rows x 2 columns]

========== Cabin ==========

           Value  Count
0            NaN    687
1             G6      4
2    C23 C25 C27      4
3        B96 B98      4
4             F2      3
..           ...    ...
143          E17      1
144          A24      1
145          C50      1
146          B42      1
147         C148      1

[148 rows x 2 columns]

========== Embarked ==========

  Value  Count
0     S    644
1     C    168
2     Q     77
3   NaN      2

# Step 19: Display Missing-Value Summary

In [22]:
# ==========================================================
# Step 19: Display Missing-Value Summary
# ==========================================================

missing_summary_df = inspector.show_missing_data()  # Displays missing-value counts and percentages

          Missing Values  Missing Percentage (%)
Age                  177                   19.87
Cabin                687                   77.10
Embarked               2                    0.22